### PR TITLE
fix(@angular-devkit/build-angular): allow verbose in dev-server

### PR DESCRIPTION
**Pull request by mantyz**
This option don't work:
```json
"serve": {
          "options": {
            "verbose": true,
          }
```
 Fixed it.

### CODE REVIEW

**Comment by filipesilva** [comment]
At the moment we aren't looking to add more passthrough options to the `dev-server` builder. You can add this option to `browser` builder options and it will used in the `dev-server` as well though.

**Comment by mantyz** [comment]
@filipesilva Thanks for answer. 
I was confused by the fact that you can set this option in `serve.options`, but this do not work.

**Comment by filipesilva** [comment]
That is pretty confusing, and shouldn't be there really. Will remove, thank you for clarifying!

**Comment by mantyz** [comment]
@filipesilva Also remove this option from [angular-cli schema](https://github.com/angular/angular-cli/blob/8e69b3b9b9a3b5a6e87c2eaa9471adcbaa82326b/packages/%40angular/cli/lib/config/schema.json#L1018-L1021), please. Thank you.

**Pull request closed without merging**
