### PR TITLE
fix(@schematics/angular): Add support for ES2017 proposals

### PR DESCRIPTION
**Pull request by markgoho**
Add support for ES7 proposals such as Object.values and Object.entries, fixes angular/angular-cli#9111

### CODE REVIEW

**Comment by markgoho** [comment]
Sorry guys, I just can't seem to get the commit messages right. @filipesilva has tried to walk me through rebasing the commit but it never seems to work. Can someone handle that?

**Comment by trotyl** [comment]
`Object#values` and `Object#entries` are ES8 (ES2017) features

**Comment by markgoho-EDT** [comment]
@trotyl you're absolutely right, we should make a PR to Core-JS after this one is merged 👍 https://github.com/zloirock/core-js#ecmascript-7-proposals

**Comment by markgoho** [comment]
@trotyl you're absolutely right, we should make a PR to Core-JS after this one is merged 👍 https://github.com/zloirock/core-js#ecmascript-7-proposals

**Comment by clydin** [comment]
Thank you for the contribution.  However, as noted in the referenced issue, only polyfills required by Angular itself are intended to be included by default.

And in regards to the commit message, you almost had it right.  `schematics` and `angular` are backwards (should be `@schematics/angular`).

**Pull request closed without merging**
