### PR TITLE
fix(@angular-devkit/build-angular): Remove space in "${options.host}: ${options.port}"

### PR DESCRIPTION
**Pull request by guuurgle**

### CODE REVIEW

**Comment by filipesilva** [comment]
Aside from the changes themselves, there's two problems:
- the CLA stuff as described by the bot
- the commit itself (not just the PR title) should be `fix(@angular-devkit/build-angular): Remove space in "${options.host}: ${options.port}"`

**Comment by guuurgle** [comment]
I signed it!

**Comment by guuurgle** [comment]
@filipesilva Fixed the commit message, thanks for the heads-up!

**Comment by filipesilva** [comment]
And it's in, thank you!

**Pull request merged**
