### PR TITLE
fix(@angular-devkit/devkit): fix incorrect implementation of schematic interface

### PR DESCRIPTION
**Pull request by elhadiahmed**
fix the SchematicImpl class incorrectly implementing the Schematic interface

resolve issue #75

### CODE REVIEW

**Comment by elhadiahmed** [comment]
yes, sorry about that this one should cover it I believe unless I am missing something else, I am still new to the open source contributions and I really appreciate your patience 😄

**Comment by elhadiahmed** [comment]
@hansl I tried to ammend my commit message with the correct scope (same name of inside the package.json) but I still get the same error on the ci tool

isn't the packageJsonPaths used in the validate-commits.ts file is reading all package.json files inside the repo and adding it to the packages array ?

```
b477fb5 fix(@angular-devkit/devkit): fix the dependencies of the corrected schematic interface
  The following commit has a scope that does not exist:
```

**Comment by hansl** [comment]
You need to squash your commits so there's only 1 commit left with that line. We do not allow merge commits on master. Here's a quick guide on how to squash: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

In the future, you can change the top commit by using `git commit --amend`, and force pushing to your original branch.

Thanks!

**Comment by hansl** [comment]
PS: right now you have 5 commits in this PR, so you would need to squahs the last 4 into the first one, and rewrite the commit message for that commit. The error is coming from your merge commit which we don't allow.

**Comment by elhadiahmed** [comment]
@hansl I am a bit puzzled regarding the scope error, isn't ```@angular-devkit/devkit``` is the correct scope name ?

```Found 1 commits...
  The following commit has a scope that does not exist:
    929f613 fix(@angular-devkit/devkit): fix incorrect implementation of schematic interface
1 commits were found invalid...
A fatal error happened. See details above.
```

**Comment by elhadiahmed** [comment]
@hansl the integration tests are timing out, is there something I can do about it ? or shall you rebuild ?

**Comment by hansl** [comment]
It's okay _for this PR_ to ignore :)

**Comment by elhadiahmed** [comment]
Great, thank you so much.

**Pull request merged**
