### PR TITLE
feat(@ngtools/webpack): add .tsx support

### PR DESCRIPTION
**Pull request by urish**
This allows for mixed Angular and React code in the same project, and should address angular/angular-cli#8046.

If you wish to merge it and need me to add tests or anything, please let me know and I will try to do so ASAP. Thanks :)

### CODE REVIEW

**Comment by lygstate** [comment]
is that possible to add a small react test for stop regression

**Comment by lygstate** [comment]
I am not familiar with ngtools sorry for that

**Comment by urish** [comment]
No worries, I will take for input from the maintainers then :)

**Comment by urish** [comment]
Hi @clydin, would love to have your feedback about this PR. Cheers!

**Comment by urish** [comment]
Yay!

**Pull request merged**
