### PR TITLE
feat(@schematics/angular): upgrade to ng 5.2.0

### PR DESCRIPTION
**Pull request by akkumar**
ng 5.2.x released ~~and supports typescript 2.6.x as well~~. 

More details here at - 
https://blog.angular.io/angular-5-2-now-available-312d1099bd81 . 

Upgrade the generated package.json to refer to 5.2.x

### CODE REVIEW

**Comment by akkumar** [comment]
```console
> concurrently "npm run serve" "npm run protractor" --kill-others --success first

sh: 1: concurrently: Permission denied
```

It is not obvious if the bug is related to this commit though.

**Comment by filipesilva** [comment]
@akkumar that was a flake in the CI and is not related to your PR. I have restarted that CI job. Thanks for updating these dependencies!

**Comment by clydin** [comment]
This is blocked on https://github.com/angular/angular-cli/pull/9097

**Comment by cyrilletuzi** [comment]
We should not update to TS 2.6 yet, there is an important issue with the language service which is not working anymore in TS 2.6 : angular/angular#21591

**Comment by akkumar** [comment]
Thanks @cyrilletuzi for bringing this one up. 

For now - I have reverted the ts 2.6 change back to what it was ( 2.5.3 ) to avoid issues. 

ng has been upgraded to 5.2.x though (with ts at 2.5.3 as before ).  Because it is back to 2.5.3 it should also not be dependent anymore on  angular/angular-cli#9097 - the issue that @clydin had referred to as well. 

@filipesilva @Brocco - can you help check this one and get it in as ng 5.2.x would still be compatible with 2.5.x , I assume ? 

Let me know your comments on the same.

**Comment by cyrilletuzi** [comment]
For info, even if angular/angular#21591 is not marked as fixed, I don't have anymore problems with TypeScript 2.6 and VS Code Language Service. I think the extension patched the issue inside itself, so it should be safe to upgrade to TS 2.6.

**Pull request merged**
