### PR TITLE
feat(@angular-devkit/build-angular): add watch mode to server

### PR DESCRIPTION
**Pull request by Toxicable**
Adds watch mode into server build

### CODE REVIEW

**Comment by tobi-or-not-tobi** [comment]
@Toxicable I got a notion of this PR on your talk at ng-air today - great job! I'm wondering if this is a generic solution, so it can be used for building other apps then universal as well based on file changes. I'm after a watch mode for libraries, see #730. Ideally, we can configure watch modes for specific apps/project.

**Comment by Toxicable** [comment]
@tobi-or-not-tobi No this wont help with your issue sorry.
This is for Universal only, since libraries undergo a much different build/bundle process it cannot be applied to that either.

**Comment by kondi** [comment]
Is it possible to have some explanation or info about "further discussion"? Would be good to have this option soon.

**Review by filipesilva — APPROVED** [review]

**Comment by filipesilva** [comment]
@kondi we discussed this last friday and I think this PR is good to get in as is.

**Comment by mgol** [comment]
It doesn't seem to be working correctly for me with `@angular-devkit/build-angular` `0.7.0-beta.1`. Under my project's `architect` key I have the `server` target defined as follows:
```js
"server": {
  "builder": "@angular-devkit/build-angular:server",
  "options": {
    "outputPath": "dist/server",
    "main": "src/main.server.ts",
    "tsConfig": "src/tsconfig.server.json",
    "watch": true
  }
}
```
There is no error when I run:
```
ng run phoenix:server
```
it compiles but it then exits immediately, not entering `watch` mode.

**Comment by mgol** [comment]
Comparing the code of the browser and server parts I see that the browser one doesn't complete the observable in watch mode:
https://github.com/angular/devkit/blob/v6.1.0-beta.1/packages/angular_devkit/build_angular/src/browser/index.ts#L111
while the server one has no special logic for watch here:
https://github.com/angular/devkit/blob/v6.1.0-beta.1/packages/angular_devkit/build_angular/src/server/index.ts#L84
Can that be a problem?

**Comment by Toxicable** [comment]
@mgol Yup it was the problem, just needed a simple check.
Should be fixed in the version that was just released

**Pull request merged**
