### PR TITLE
fix(@schematics/angular): sync up application and component spec schematics

### LINKED ISSUE #182: __name@dasherize__.component.spec.ts don't use async in spec case
Component spec file scheme is old and not consistent with spec in new app since it's not using async() in spec case, should be used by default.

component:
https://github.com/angular/devkit/blob/master/packages/schematics/angular/component/files/__path__/__name%40dasherize%40if-flat__/__name%40dasherize__.component.spec.ts

spec in new app:
https://github.com/angular/devkit/blob/master/packages/schematics/angular/application/other-files/app.component.spec.ts

### PR DESCRIPTION
**Pull request by trimeyko**
Fix #182

add blank lines to sync up with other spec schematics in app.component.spec,
add async usage to component schematics

### CODE REVIEW

**Review by hansl — APPROVED** [review]

**Comment by hansl** [comment]
This should be in the next major (0.4 of DevKit, 6.0 of CLI).

**Comment by Brocco** [comment]
@trimeyko Could you please rebase this PR?

**Comment by trimeyko** [comment]
@Brocco sure, but is there any decision on async() in default schematics ? See https://github.com/angular/devkit/pull/224 discussion.

**Comment by alexeagle** [comment]
Sorry @trimeyko  - this got lost when we moved back to the angular/angular-cli repo. If you still think this pull request is relevant, could you please re-base on that repo and open a new PR there? Thanks and sorry for the extra churn.

**Pull request closed without merging**
